apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-tableau
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    ingress.kubernetes.io/proxy-body-size: "15m"
    nginx.org/proxy-connect-timeout: "300s"
    nginx.org/proxy-read-timeout: "60s"
    nginx.org/client-max-body-size: "15m"
spec:
  backend:
    serviceName: default-http-backend
    servicePort: 80
  rules:
  - host: tableau.stouffcapital.com
    http:
      paths:
      - path: /
        backend:
          serviceName: com-stouffcapital-tableau
          servicePort: 5000
