apiVersion: v1
kind: Service
metadata:
  name: com-stouffcapital-tableau
  namespace: tableau
  labels:
    app: com-stouffcapital-tableau
spec:
  ports:
  - port: 5000
  selector:
    app: com-stouffcapital-tableau
  clusterIP: None
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: com-stouffcapital-tableau
  namespace: tableau
  labels:
    app: com-stouffcapital-tableau
  annotations:
        backup.velero.io/backup-volumes: tableau-persistent-storage
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: com-stouffcapital-tableau
    spec:
      containers:
      - image: stouffcapital/com-stouffcapital-tableau
        name: com-stouffcapital-tableau
        env:
        - name: APP_SECRET
          valueFrom:
            secretKeyRef:
              name: tableau
              key: app-secret
        - name: POSTGRES_HOST
          value: timescaledb
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: timescaledb
              key: postgres-password
        - name: BASIC_AUTH_USERNAME
          valueFrom:
            secretKeyRef:
              name: ib
              key: backend-user
        - name: BASIC_AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ib
              key: backend-password
        - name: IB_HOST
          value: https://ib.stouffcapital.com
        - name: GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: tableau
              key: github-client-id
        - name: GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: tableau
              key: github-client-secret
        - name: S3_HOST
          value: http://s3-minio-service.storage.svc.cluster.stouffcapital.tech:9000
        - name: S3_ACCESSKEY
          valueFrom:
            secretKeyRef:
              name: s3
              key: s3-accesskey
        - name: S3_SECRETKEY
          valueFrom:
            secretKeyRef:
              name: s3
              key: s3-secretkey
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: tableau-persistent-storage
          mountPath: /app/app/static/data
      volumes:
      - name: tableau-persistent-storage
        persistentVolumeClaim:
          claimName: com-stouffcapital-tableau-pv-claim
